spring:
  datasource:
    url: jdbc:h2:mem:public;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS \"idxterminal\"
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
flyway:
  enabled: true
  baselineOnMigrate: true
  locations: db/migration/common, db/migration/test